plugins:
    - jekyll-relative-links
relative_links:
    enabled: true
    collections: true
include:
    - playground.md
    - getting-started.md
    - faq.md
    - build-extension.md
    - register-extension.md
    - SDK.md
    - submit-extension.md

theme: jekyll-theme-cayman